### ISSUE TITLE
electron:build add session to the project

### ISSUE THREAD

**Issue by LingHanChuJian** [nklayman/vue-cli-plugin-electron-builder#315] opened 2019-06-23 09:45 UTC
**Describe the bug**
When I tried to package Win with a session, the electronics didn't work properly and the registered app:// protocol could not be recognized.

**To Reproduce**
1. vue create {project-name}
2. select plugins
  -  bebel
  -  eslint
3. run "vue add electron-builder"
4. run "yarn electron:build"

**Expected behavior**
Open the win-unpacked folder and run {Project}.exe, it should open an app window with the default vue template

**Screenshots**
The code is as follows:
```javascrapy
function createWindow () {
  // Create the browser window.
  win = new BrowserWindow({ 
    width: 800, 
    height: 600, 
    webPreferences: {
      nodeIntegration: true,
      session: session.fromPartition('win')
    } 
  })

  if (process.env.WEBPACK_DEV_SERVER_URL) {
    // Load the url of the dev server if in development mode
    win.loadURL(process.env.WEBPACK_DEV_SERVER_URL)
    if (!process.env.IS_TEST) win.webContents.openDevTools()
  } else {
    createProtocol('app')
    // Load the index.html when not in development
    win.loadURL('app://./index.html')
  }

  win.on('closed', () => {
    win = null
  })
}
```

electron:build  result:
![bug](https://user-images.githubusercontent.com/22723360/59974350-e0013f80-95dd-11e9-9c36-4c691d1b3c48.jpg)

**Environment (please complete the following information):**
 - OS and version:  Win10 64Bit
 - node version:  11.7.0
 - npm version: 6.5.0
 - yarn version (if used): 1.15.2
 - vue-cli-plugin-electron-builder version : 1.3.5
 - electron version:  5.0.0 or 5.0.0 +
 - other vue plugins used: bebel, eslint

**Comment by nklayman** [comment] 2021-02-23 20:11
Duplicate of #1150, see solution there.

**Closed by nklayman** 2021-02-23 20:11 UTC
