### ISSUE TITLE
missing style path

### ISSUE THREAD

**Issue by hanjeahwan** [nklayman/vue-cli-plugin-electron-builder#58] opened 2018-08-27 11:10 UTC
**Describe the bug**

style path and which line of css is not show in dev tools

**To Reproduce**

import any css file in main.js and use the class from that css file at any .vue html

**Expected behavior**
should show this css class is from which css file and which line

![image](https://user-images.githubusercontent.com/21311478/44656760-c37f8f80-aa2c-11e8-9886-12411164e331.png)

**Screenshots**

![test](https://user-images.githubusercontent.com/21311478/44656690-697eca00-aa2c-11e8-90ef-73ec1d0f6eb9.png)

**Environment (please complete the following information):**

 - OS and version: win10
 - Node version: v8.11.3
 - npm version: 5.6.0
 - yarn version (if used): 1.9.4
 - vue-cli-plugin-electron-builder version : ^1.0.0-rc.1

**Comment by nklayman** [comment] 2018-08-27 15:19
The same thing happens in the regular serve command. This is because webpack injects the styles into the `index.html`. This issue is not related to this plugin, rather it is caused by vue-cli, so I will close this issue.

**Closed by nklayman** 2018-08-27 15:19 UTC
