### ISSUE TITLE
HMR stopped working with RC10

### ISSUE THREAD

**Issue by CoolHandDev** [nklayman/vue-cli-plugin-electron-builder#165] opened 2018-12-22 22:44 UTC
**Describe the bug**
Hot reloading stopped working with rc10

**To Reproduce**
vue add electron-builder
npm run electron:serve

**Expected behavior**
Electron is expected to launch, dev-tools to open, and HMR ready. HMR with rc9 was working fine

**Screenshots**

<img width="827" alt="screen shot 2018-12-22 at 5 40 07 pm" src="https://user-images.githubusercontent.com/15180441/50379186-b8222680-0610-11e9-9171-939d29acb568.png">

**Environment (please complete the following information):**
 - OS and version: MacOS Mojave 10.14.2
 - node version: 11.5.0
 - npm version: 6.4.1
 - yarn version (if used): 
 - vue-cli-plugin-electron-builder version :  v1.0.0-rc.10
 - electron version:  4.0.0
 - other vue plugins used: 
 - custom config for vcp-electron-builder: 
 - (if possible) link to your repo: 

**Additional context**

**Comment by rakakhrl** [comment] 2018-12-23 07:08
I have the same issue, but changing it to rc9 still doesnt fix it. Is it because i use electron v2?

**Comment by LukasBombach** [comment] 2018-12-23 12:32
@CoolHandDev thank you, I had that exact same issue and that fixed it for me!

**Comment by CoolHandDev** [comment] 2018-12-23 13:00
Here are other related material

https://github.com/webpack/webpack-dev-server/issues/1604
https://github.com/sockjs/sockjs-node/pull/247
https://github.com/webpack/webpack-dev-server/pull/1608

**Comment by nklayman** [comment] 2018-12-23 16:09
Closing as the issue is related to another package. Thanks for posting a solution!

**Closed by nklayman** 2018-12-23 16:09 UTC
