### ISSUE TITLE
Use with mongoose

### ISSUE THREAD

**Issue by Granipouss** [nklayman/vue-cli-plugin-electron-builder#57] opened 2018-08-27 08:42 UTC
Hi,

I am trying to build an electron app with vue and mongoose. But mongoose act as if it was loaded on a browser (which is not working).

```js
const mongoose = require('mongoose')

console.log(mongoose.connect) // => "undefined"
```

I strongly suspect that this is because the renderer is built in webpack targeting `web`  isntead of `electron-renderer` (https://webpack.js.org/configuration/target/). But I don't know how to test that.

Can you help me with that ?

Additionally, maybe that can be solved with a vue config file, but I don't know how.

 - OS and version: Windows 10
 - Node version: 10.9.0
 - vue-cli-plugin-electron-builder version : 1.0.0-rc.1

**Comment by nklayman** [comment] 2018-08-27 15:09
The issue isn't that it is set for web target as I set it to `electron-renderer`. The issue was that the code for determining externals would immediately return false if a dependency had an `index.js` instead of waiting for other checks. I fixed it in commit 4df3aeb63d67034b0597d55382277bee67d14826, and it will be released in 1.0.0-rc.2. To have the fix now instead of waiting for 1.0.0-rc.2, set vue-cli-plugin-electron-builder's version to `nklayman/vue-cli-plugin-electron-builder`. This will have it pull the code directly from the github repository instead of from the latest release.

**Closed by nklayman** 2018-08-27 15:09 UTC
