### ISSUE TITLE
Webstorm debugger not working

### ISSUE THREAD

**Issue by kusyka911** [nklayman/vue-cli-plugin-electron-builder#434] opened 2019-08-26 10:26 UTC
**Describe the bug**
Webstorm debugger not working with this plugin

**Screenshots**
![image](https://user-images.githubusercontent.com/24293461/63684042-a5499c80-c804-11e9-82e3-8ac508e4df80.png)

**Environment (please complete the following information):**
 - OS and version: ubuntu 18 lts
 - node version: 10.16.2 lts
 - vue-cli-plugin-electron-builder version:  ^1.4.0
 - electron version 6.0: 
 - other vue plugins used: typescript
 - custom config for vcp-electron-builder: 
```
    electronBuilder: {
      mainProcessFile: 'src/electron/background.ts',
      chainWebpackMainProcess: (config) => {
        config.resolve.alias.set('@', path.join(__dirname, 'src'));
      },
      mainProcessTypeChecking: true,
      builderOptions: {},
    },
```

**Additional context**
webstorm version: 2019.2 stable
console logs:
```
/home/vlad/projects/playground/node_modules/electron/dist/electron --type=renderer --field-trial-handle=696921918122827264,2031100527710197737,131072 --disable-features=SpareRendererForSitePerProcess --lang=en-US --standard-schemes=app --secure-schemes=app --bypasscsp-schemes --cors-schemes --fetch-schemes --service-worker-schemes --app-path=/home/vlad/projects/playground/dist_electron --node-integration --no-sandbox --no-zygote --background-color=#fff --num-raster-threads=2 --enable-main-frame-before-activation --service-request-channel-token=6451743705860089792 --renderer-client-id=6 --no-v8-untrusted-code-mitigations --shared-fil[25385]: ../../third_party/electron_node/src/inspector_agent.cc:793:bool node::inspector::Agent::StartIoThread(): Assertion `(client_) != nullptr' failed.
```

P.S. latest VScode with guilde from [here](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/recipes.html#debugging-with-vscode) also not work for me.

**Comment by mfarahmand98** [comment] 2019-08-28 15:47
The plugin warns you during the installation that the dev tools break with Electron v6 and must be disabled. This is yet to be implemented.

**Comment by rickbsgu** [comment] 2019-09-21 14:49
I presume this is also true for vscode?  Can't debug main process...

**Comment by nklayman** [comment] 2020-06-28 18:09
Duplicate of #535.

**Closed by nklayman** 2020-06-28 18:09 UTC
