### ISSUE TITLE
background.js is not compiled by Babel

### ISSUE THREAD

**Issue by alexanderl19** [nklayman/vue-cli-plugin-electron-builder#768] opened 2020-05-22 05:44 UTC
**Describe the bug**
The background.js file generated by the plugin does not seem to be compiled by babel.

**To Reproduce**

1. Create a class with [public/private variable](https://github.com/tc39/proposal-class-fields) in background.js
```
class TestClass {
    publicVar;
    #privateVar;
}
```
2. Run `npm run electron:serve` or `npm run electron:build`
```
Module parse failed: Unexpected token (12:13)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
| class TestClass {
>     publicVar;
|     #privateVar;
| }
```

**Expected behavior**
The code is compiled by Babel, like when it is run in App.vue.
```
created() {
    class TestClass {
        publicVar;
        #privateVar;
    }
},
```

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS and version: Windows 10 Pro 1909
 - node version: 12.16.1
 - npm version: 6.14.3
 - yarn version (if used): N/A
 - vue-cli-plugin-electron-builder version : 1.4.6
 - electron version: 9.0.0
 - other vue plugins used: 
```
"devDependencies": {
    "@vue/cli-plugin-babel": "~4.3.1",
    "@vue/cli-plugin-eslint": "~4.3.1",
    "@vue/cli-plugin-router": "^4.3.1",
    "@vue/cli-service": "^4.3.1",
    "@vue/eslint-config-prettier": "^6.0.0",
    "babel-eslint": "^10.1.0",
    "electron": "^9.0.0",
    "electron-icon-builder": "^1.0.2",
    "eslint": "^7.0.0",
    "eslint-plugin-prettier": "^3.1.3",
    "eslint-plugin-vue": "^6.2.2",
    "lint-staged": "^10.2.4",
    "prettier": "^2.0.5",
    "sass": "^1.26.5",
    "sass-loader": "^8.0.2",
    "snyk": "^1.323.2",
    "vue-cli-plugin-electron-builder": "~1.4.6",
    "vue-template-compiler": "^2.6.11"
  },
```
 - custom config for vcp-electron-builder: N/A
 - (if possible) link to your repo: 
https://github.com/alexanderl19/vue-cli-plugin-electron-builder-bug-demo
[Example in background.js](https://github.com/alexanderl19/vue-cli-plugin-electron-builder-bug-demo/blob/f7fb08395d0372c21019c8df9691ba2f90b36104/src/background.js#L11)
[Example in App.vue](https://github.com/alexanderl19/vue-cli-plugin-electron-builder-bug-demo/blob/f7fb08395d0372c21019c8df9691ba2f90b36104/src/App.vue#L17)

**Additional context**
```
module.exports = {
    presets: ["@vue/cli-plugin-babel/preset"],
};
```
^ babel.config.js

[@vue/cli-plugin-babel/preset](https://github.com/vuejs/vue-cli/tree/dev/packages/@vue/cli-plugin-babel#configuration)
[@vue/babel-preset-app](https://github.com/vuejs/vue-cli/tree/dev/packages/@vue/babel-preset-app#stage-3-or-below)
[@babel/plugin-proposal-class-properties](https://babeljs.io/docs/en/next/babel-plugin-proposal-class-properties.html)

**Comment by nklayman** [comment] 2020-05-22 21:50
Babel is not used as electron uses a recent version of nodejs which supports most features you will need. The issue you encountered is a duplicate of #204, instructions on using babel in the main process are listed there.

**Closed by nklayman** 2020-05-22 21:50 UTC
