### ISSUE TITLE
mac build: fsevents Unexpected character (1:0)

### ISSUE THREAD

**Issue by Venipa** [nklayman/vue-cli-plugin-electron-builder#1333] opened 2021-04-20 22:42 UTC
**Describe the bug**
If i want to build the mac dmg via github actions it runs until it wants to bundle the release:
Mac os build logs can be found here: https://github.com/Venipa/ytmdesktop2/runs/2395324300

```
-  Bundling main process...
 ERROR  Failed to compile with 1 errors10:35:03 PM

 error  in ./node_modules/fsevents/fsevents.node

Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)

 @ ./node_modules/fsevents/fsevents.js 13:15-41
 @ ./node_modules/chokidar/lib/fsevents-handler.js
 @ ./node_modules/chokidar/index.js
 @ ./node_modules/sass/sass.dart.js
 @ ./src/app/utils/webContentUtils.ts
 @ ./src/app/main.ts
 @ ./src/background.ts
 @ multi ./src/background.ts
```

**To Reproduce**
- get your mac instance/machine
- `git clone https://github.com/Venipa/ytmdesktop2`
- `yarn release --mac` or just `yarn release`

**Expected behavior**
No Error 👍 

**Screenshots**
![image](https://user-images.githubusercontent.com/17952364/115472416-1b9cdd00-a23a-11eb-88e6-a7fd6e58b048.png)

**Environment (please complete the following information):**
 - custom config for vcp-electron-builder: https://github.com/Venipa/ytmdesktop2/blob/master/vue.config.js
 - (if possible) link to your repo: https://github.com/Venipa/ytmdesktop2

**Additional context**
Last run with failed mac-os build: https://github.com/Venipa/ytmdesktop2/runs/2395324300 (contains the error)

**Comment by Venipa** [comment] 2021-04-20 22:59
ok, i've added a resolution to a previous version of chokidar and it works for now
```
// in package.json
"resolutions": {
    "chokidar": "2.1.8"
  },
```

well its just a workaround

**Comment by nklayman** [comment] 2021-04-24 18:50
I tried the repo you shared and it works just fine, even without the chokidar version resolution (I am on Linux though, so that might negate the issue). I don't have a mac to test it unfortunately. The Github action run you linked to actually succeeded on Mac, but failed on windows because of an unrelated issue. Can you share a link to a workflow run that actually failed on Mac? From what you posted, it seems that marking chokidar as an external would fix it.

**Comment by Venipa** [comment] 2021-04-24 19:10
> I tried the repo you shared and it works just fine, even without the chokidar version resolution (I am on Linux though, so that might negate the issue). I don't have a mac to test it unfortunately. The Github action run you linked to actually succeeded on Mac, but failed on windows because of an unrelated issue. Can you share a link to a workflow run that actually failed on Mac? From what you posted, it seems that marking chokidar as an external would fix it.

yes the mac build reported "succeeded" but it still failed which resulted in no publish:
![image](https://user-images.githubusercontent.com/17952364/115970253-83f10480-a541-11eb-9da8-64daa80df7e4.png)

**Comment by undergroundwires** [comment] 2021-12-31 20:35
I had the same problem only for running `vue-cli-service test:unit` command on macOS. Solved it by setting `fsevents` inside as external in `configureWebpack` of `vue.config.js`:

```js
module.exports = defineConfig({
    configureWebpack: {
        externals: ['fsevents'],
    },
```

Or:

```js
module.exports = defineConfig({
    configureWebpack: {
        externals: {
            'fsevents': 'require("fsevents")'
        },
    },
```

Both works.

**Comment by nklayman** [comment] 2022-01-02 05:15
Seems like this is a duplicate of #712 then. Thanks for the help @undergroundwires.

**Closed by nklayman** 2022-01-02 05:15 UTC
