### ISSUE TITLE
 error  '__static' is not defined  no-undef

### ISSUE THREAD

**Issue by iamzaizai** [nklayman/vue-cli-plugin-electron-builder#1340] opened 2021-04-25 07:54 UTC
**Describe the bug**
vue.js 
```
<script>
import path from 'path';

export default {
    mounted () {
        console.log(path.join(__static, '/static/text.png'));
    }
}
```

**error**
```
 error  '__static' is not defined  no-undef
```

????

**Comment by nklayman** [comment] 2021-04-29 00:28
Duplicate of #470, solution is to add `/ * global __static * /` to the top of any JS you use `__static` in.

**Closed by nklayman** 2021-04-29 00:28 UTC

**Comment by iamzaizai** [comment] 2021-04-29 03:37
Thanks  @nklayman
