### ISSUE TITLE
use websocket error: Module parse failed: Unexpected token

### ISSUE THREAD

**Issue by StringKe** [nklayman/vue-cli-plugin-electron-builder#602] opened 2019-12-24 02:25 UTC
**Describe the bug**
Using webscoket in `background.js` fails to start `yarn electron: dev`

**To Reproduce**
1. create server.js
```javascript
import ws from 'ws';
import http from 'http';
import notify from './notify';

class Server {
  _webSocketServer;

  _webSocketLoop;

  _webSocketCheck;

  Start() {
    const httpServer = http.createServer((req, res) => {
      req.on('error', error => notify.log('HTTP Request error', error));
      res.on('error', error => notify.log('HTTP Response error', error));
      res.end();
    })
      .on('error', error => notify.log('HTTP error', error));

    httpServer.listen(7891, '0.0.0.0', () => {
      this.webSocketServer(httpServer);
      notify.log('start success', {});
    });

    setInterval(() => {
      notify.log('send test message to client');
    }, 1000);
  }

  webSocketServer(httpServer) {
    const webSocketsOptions = {
      server: httpServer,
    };
    this._webSocketServer = new ws.Server(webSocketsOptions);
    this._webSocketServer
      .on('error', error => notify.log('websocket', error))
      .on('connection', (_client, req) => {
        const remoteAddress = req.headers['x-real-ip'] === undefined
          ? `${req.connection.remoteAddress}:${req.connection.remotePort}`
          : `${req.headers['x-real-ip']}:${req.headers['x-real-port']}`;
        this.controller(_client, remoteAddress);
        notify.log(`address => ${remoteAddress} status => connection`);
      });
    this._webSocketLoop = setInterval(() => this.webSocketPing(), 60 * 1000);
  }

  controller(client, remoteAddress) {
    if (this.checkController !== undefined) {
      this.checkController.close(1001, 'to many connections');
    }
    const onLog = data => this.webSocketMessage(data);
    client
      .on('error', (err) => {
        notify.removeListener('log', onLog);
        this.webSocketDestroyClient(client);
        notify.error(client.protocol, remoteAddress, err);
      })
      .on('close', (code, reason) => {
        notify.removeListener('log', onLog);
        this.webSocketDestroyClient(client);
        notify.log(`address: ${remoteAddress} destroy client`, {
          code,
          reason,
        });
      })
      .on('message', async (msg) => {
        const message = await JSON.parse(msg);
        if (message !== undefined && message.cmd !== undefined && message.ts !== undefined) {
          this.executeCommand(message);
        }
      });
    this.checkController = client;
    notify.on('log', onLog);
  }

  executeCommand(message) {
    const { cmd, ts } = message;
    this.webSocketMessage({
      cmd,
      ts,
      msg: "can't find command",
    });
  }

  webSocketDestroyClient(client) {
    client.close();
    client.terminate();
    client.removeAllListeners();
  }

  webSocketMessage(data) {
    if (this._webSocketCheck.readyState === ws.OPEN) {
      this._webSocketCheck.send(JSON.stringify(data));
    }
  }

  webSocketPing() {
    this._webSocketServer.clients.forEach(client => client.ping());
  }
}

export default Server;
```
2. create notify.js
```javascript
import { EventEmitter } from 'events';

const log4js = require('log4js');

const logger = log4js.getLogger();

class Notify extends EventEmitter {
  logs = [];

  constructor() {
    super();
    this.on('system', (message, data) => this.log(message, data));
  }

  log(message, data) {
    if (this.logs.length > 500) {
      this.logs.shift();
    }
    const log = {
      message,
      data,
    };
    logger.info(message, data);
    this.emit('log', log);
    this.logs.push(log);
  }
}

export default new Notify();
```

3. yarn add log4js ws
4.using background.js in server.js
```javascript
import Server from './server';

const server = new Server();
server.Start();
```

**Expected behavior**
start webscoket server

**Screenshots**
![image](https://user-images.githubusercontent.com/31089228/71389391-2a1fb800-2637-11ea-924b-0daf2edd62b2.png)

**Environment (please complete the following information):**
 - OS and version: macos 10.15.2 / windows 10 1903
 - node version: 12.13.0
 - npm version:6.13.1
 - yarn version (if used): 1.19.2 
 - vue-cli-plugin-electron-builder version : 1.4.4
 - electron version: 6.1.7
 - other vue plugins used: vue router, vuex 
 - custom config for vcp-electron-builder: none
 - (if possible) link to your repo: [electron-test](https://github.com/StringKe/electron-test)

**Additional context**

**Comment by nklayman** [comment] 2019-12-29 00:26
This is a duplicate of #204. Set you `vue.config.js` to:

```js
module.exports = {
  pluginOptions: {
    electronBuilder: {
      chainWebpackMainProcess: config => {
        config.module
          .rule('babel')
          .test(/\.js$/)
          .exclude.add(/node_modules/)
          .end()
          .use('babel')
          .loader('babel-loader')
          .options({
            presets: [['@babel/preset-env', { modules: false }]],
            plugins: ['@babel/plugin-proposal-class-properties']
          })
      }
    }
  }
}
```
Explanation here: https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/204#issuecomment-466116527.

**Closed by nklayman** 2019-12-29 00:26 UTC
