### ISSUE TITLE
Allow build if tslint fails

### ISSUE THREAD

**Issue by LittleHuba** [nklayman/vue-cli-plugin-electron-builder#134] opened 2018-11-16 18:20 UTC
**Is your feature request related to a problem? Please describe.**
Building the app is impossible when linting finds errors. Even if the error does not actually break the app.

**Describe the solution you'd like**
Let the user decide if the build should be aborted when linting finds errors or to continue with the build.

**Describe alternatives you've considered**
Also okay would be if you list all results of linting but continue with the build process.

**Additional context**
This is the error message when linting finds any errors:
```
(node:27854) UnhandledPromiseRejectionWarning: Build failed with errors.
(node:27854) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:27854) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by nklayman** [comment] 2018-11-20 01:39
The issue is that vue-cli rejects the promise if linting fails. It would be difficult to tell the difference between that and a major error. Open an issue on Vue CLI instead that requests resolving the promise if the only error is tslint.

**Closed** 2018-11-20 01:39 UTC
