### ISSUE TITLE
Add flag to skip "electron-builder"

### ISSUE THREAD

**Issue by nathanblair** [nklayman/vue-cli-plugin-electron-builder#1161] opened 2020-12-02 19:01 UTC
**Is your feature request related to a problem? Please describe.**
This seems to be the most succinct repository for embedding Electronjs into a vue.js app. However, the command to embed the Electronjs framework also performs a "packaging" step (I believe the documentation calls this phase the "Electron-Builder build phase).

I would love for the ability to skip the packaging/Electron-Builder build phase and just create a bundle with the Electron boilerplate embedded.

The opposite of this has basically been handled by allowing the `--skipBundle` flag.

**Describe the solution you'd like**
Add a flag (and the ability) that handles skipping the latter part of the `electron:build` command - the part that uses electron-builder to produce an installer for the target platform.

**Describe alternatives you've considered**
I'm honestly not aware of any alternatives to using this package for just the former portions of its `electron:build` functionality.

I am not an expert at vue.js or Electronjs so this feature request may be readily accessible without the need for this package already; I just don't know how to do it and would certainly be receptive of suggestions.

It seems like I could run the `vue-cli-service build` to bundle up the vue app; then copy the package.json into the bundle directory. This then leaves the background.js script; but in our case this background.js script appears to undergo a transpilation with webpack or babel or some such and I'm unsure what commands may be accessible to perform this without the `electron:build` behavior.

Thanks for any support!

**Comment by nklayman** [comment] 2020-12-13 23:00
If you use `electron:build --dir`, electron-builder will not create any installers, only a bundle in `dist_electron/[PLATFORM]-unpacked`, and the executable is `dist_electron/[PLATFORM]-unpacked/[APP NAME]`. Is this what you want?

Also a duplicate of #1033

**Comment by nathanblair** [comment] 2020-12-18 16:17
I was hoping more for the ability to not even create any executables. We only need to do the rendered build and and electron main process bundle.

This shaves probably only seconds off of the build time but those seconds can add up quickly.

**Comment by nklayman** [comment] 2020-12-22 19:44
How do you deploy without the generated executable? Are you using another tool like electron-packager? The `dist_electron/[PLATFORM]-unpacked/[APP NAME]` is the least 'compiled' way to run the app. You would have to manually replicate that process to have a functioning app, which would take longer than the ~1.5 seconds that electron-builder takes to do it. I'm just trying to understand the purpose here because I don't see how it could work without electron-builder. It would be like vue-cli build emitting the JS bundle but without the `index.html`.

**Comment by pattrickrice** [comment] 2020-12-23 18:30
I'm actually currently running into a situation where this flag would be useful. I know the plugin is "plugin-electron-builder", so not running the electron-builder stage probably seems strange. I'm currently working on trying to perform this build via bazel and being able to separate out the electron-builder stage from the render/main bundling is looking like something I need to do because I need to do some extra configuring to the environment/electron-builder configuration after the bundle stage.

**Comment by nathanblair** [comment] 2021-01-26 02:03
We need additional assets (unrelated to electron) bundled as part of a different build process in CI. And I don't want to compile to platform-specific executables until the last possible job to save on wasted build time.

The goal is to insert the pre-built electron binaries for the built-for platform as the last step. We just need to generate the electron `main.js/background.js` file before all that happens as it is platform-independent at that point.

Hopefully that makes sense? If this something not desired to be supported, that's understandable too.

**Comment by nklayman** [comment] 2021-02-11 17:45
Fixed with #1237!

**Closed by nklayman** 2021-02-11 17:45 UTC
