### ISSUE TITLE
Can't install vue dev tools electron 9.0.0

### ISSUE THREAD

**Issue by AmrBinBashir** [nklayman/vue-cli-plugin-electron-builder#850] opened 2020-06-24 07:27 UTC
**Describe the bug**
vue-devtools fails to install on electron 9.0.0.
Error message:
```
(electron) 'BrowserWindow.addDevToolsExtension' is deprecated and will be removed. Please use 'session.loadExtension' instead.
(node:3128) ExtensionLoadWarning: Warnings loading extension at C:\Users\amrba\AppData\Roaming\electron-firebase\extensions\nhdogjmejiglipccpnnnanhbledajbpd: Unrecognized manifest key 'browser_action'. Unrecognized manifest key 'update_url'. Permission 'contextMenus' is unknown or URL pattern is malformed. Cannot load extension with file or directory name _metadata. Filenames starting with "_" are reserved for use by the system.
```
**To Reproduce**
1. create new vue project.
2. add this plugin 
3. yarn electron:serve

**Environment (please complete the following information):**
 - OS and version: win 10 , 1909
 - node version: 12.8.1
 - npm version: 6.14.5
 - yarn version (if used): 1.22.0 
 - vue-cli-plugin-electron-builder version :  2.0.0-rc.2
 - electron version: 9.0.0
 - other vue plugins used: standard (bable,eslint,prettier,node-sass)
 - custom config for vcp-electron-builder:  nope
 - (if possible) link to your repo:

**Comment by nklayman** [comment] 2020-06-24 18:36
Duplicate of #776.

**Closed by nklayman** 2020-06-24 18:36 UTC
