### ISSUE TITLE
Can't get electron:serve script to launch window on v2.0.0-beta.0

### ISSUE THREAD

**Issue by alexanderl19** [nklayman/vue-cli-plugin-electron-builder#775] opened 2020-05-30 01:12 UTC
**Describe the bug**
The `electron:serve` script does not launch window on [v2.0.0-beta.0](https://github.com/nklayman/vue-cli-plugin-electron-builder/releases/tag/v2.0.0-beta.0)

```
DONE  Compiled successfully in 915ms
...
INFO  Launching Electron...
```

**To Reproduce**
Install [v2.0.0-beta.0](https://github.com/nklayman/vue-cli-plugin-electron-builder/releases/tag/v2.0.0-beta.0)
Use `vue invoke electron-builder` to generate files with the plugin
Run `npm run electron:serve` or `yarn run electron:serve`

**Expected behavior**
The window appears

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS and version: Windows 10 Pro 1909
 - node version: 12.16.1
 - npm version: 6.14.3
 - yarn version (if used): N/A
 - vue-cli-plugin-electron-builder version : 2.0.0-beta.0
 - electron version: 7.3.0
 - other vue plugins used:
```
"@vue/cli-plugin-babel": "~4.4.0",
"@vue/cli-plugin-eslint": "~4.4.0",
```
 - custom config for vcp-electron-builder: N/A
 - (if possible) link to your repo: https://github.com/alexanderl19/vue-cli-plugin-electron-builder-2.0.0-beta.0-test

**Additional context**
The IDE loses focus when `INFO  Launching Electron...` is logged.

**Comment by nklayman** [comment] 2020-05-30 05:02
Try `rm -rf node_modules && npm i` to reinstall electron as it sounds like the install may be corrupted. If that doesn't work try deleting the electron cache folder at `$LOCALAPPDATA/electron/Cache`.

**Comment by alexanderl19** [comment] 2020-05-31 02:58
No luck with either. Also, I tried changing to `vue-cli-plugin-electron-builder 1.4.6` successfully with the only change being the following.
``` js
  win = new BrowserWindow({ width: 800, height: 600, webPreferences: {
    // Use pluginOptions.nodeIntegration, leave this alone
    // See nklayman.github.io/vue-cli-plugin-electron-builder/guide/configuration.html#node-integration for more info
    nodeIntegration: process.env.ELECTRON_NODE_INTEGRATION
  } })
```
to
``` js
  win = new BrowserWindow({ width: 800, height: 600, webPreferences: {
    // Use pluginOptions.nodeIntegration, leave this alone
    // See nklayman.github.io/vue-cli-plugin-electron-builder/guide/configuration.html#node-integration for more info
    nodeIntegration: true
  } })
```
I did not reinstall any other dependencies or delete the electron cache between this change.
It works properly on 1.4.6.

**Comment by alexanderl19** [comment] 2020-05-31 05:18
I had a friend clone https://github.com/alexanderl19/vue-cli-plugin-electron-builder-2.0.0-beta.0-test and try `electron:serve`. He has never done any electron development and experiences the same behavior.

**Comment by nklayman** [comment] 2020-05-31 19:12
Duplicate of #693, upgrading to the latest 2.0 beta fixes it.

**Closed by nklayman** 2020-05-31 19:12 UTC
