### ISSUE TITLE
Running an express server in a separate process

### ISSUE THREAD

**Issue by rjoo** [nklayman/vue-cli-plugin-electron-builder#370] opened 2019-07-23 15:55 UTC
**Is your feature request related to a problem? Please describe.**
What is the best way to get an express/node.js http server running separately from Electron's main process?

**Describe the solution you'd like**
A solution worked into the existing electron:serve/build tasks.

**Describe alternatives you've considered**
I've tried creating a hidden BrowserWindow, and while that works in development it doesn't get bundled correctly in the builder. I've tried forking/spawning Node processes, but couldn't get around errors that would occur.

**Comment by king-alpha** [comment] 2019-07-29 16:08
I need similar functionality

**Comment by gultomic** [comment] 2019-07-31 12:13
me too, need suggestion where have to start for noobies

**Comment by nklayman** [comment] 2019-08-03 20:10
This appears to be a duplicate of #76. See https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/76#issuecomment-450514568 and https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/76#issuecomment-450577577 for the solution. In the worker file, you can put the code to run your express server. You may also need to mark any deps used in that file as externals by updating your `vue.config.js`:
```js
module.exports = {
  pluginOptions: {
    electronBuilder: {
      // List deps used in worker file here
      externals: ['express'],
    }
  }
}
```

**Closed by nklayman** 2019-08-03 20:10 UTC

**Comment by patarapolw** [comment] 2019-12-14 15:27
Is there an option to make `server.ts` webpacked, like `background.ts`?
