### ISSUE TITLE
Uncaught ReferenceError: __dirname is not defined

### ISSUE THREAD

**Issue by AlishaHawkward** [nklayman/vue-cli-plugin-electron-builder#906] opened 2020-07-19 17:35 UTC
**Describe the bug**
When use `import { ipcRenderer } from 'electron'` in render thread, `Uncaught ReferenceError: __dirname is not defined` occured.

**Screenshots**
![image](https://user-images.githubusercontent.com/19757919/87881030-10a5e980-ca29-11ea-9fd4-a599938db39f.png)

**Environment (please complete the following information):**
 - `vue create project` with ts
 - `vue add electron-builder`

**Comment by nklayman** [comment] 2020-07-20 06:18
Duplicate of #874, see solution there.

**Closed by nklayman** 2020-07-20 06:18 UTC
