### ISSUE TITLE
Video source not loading on production

### ISSUE THREAD

**Issue by matjazPrijatelj** [nklayman/vue-cli-plugin-electron-builder#1126] opened 2020-11-04 01:15 UTC
I've tried to build app using electron 9 and vue electron builder 2.0rc5  but the mp4 video doesn't work on production build (works using electron:serve). The message while trying to load the video from public folder was no availible source found. I've tried to downgrade electron to latest builds of 8.0 and 7.0 and same error was shown. On 6.1.12 it works as expected.

**Comment by nklayman** [comment] 2020-11-06 06:21
Duplicate of #872, try this solution: https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/872#issuecomment-656292808.

**Closed by nklayman** 2020-11-06 06:21 UTC
