### ISSUE TITLE
Default support for preload.js

### ISSUE THREAD

**Issue by nibbleswap** [nklayman/vue-cli-plugin-electron-builder#883] opened 2020-07-03 19:46 UTC
I found it very complex to cleanly set up the loading of preload.js. In the process of getting there I had to study way too much documentation and also stumbled across a few documentation inaccuracies or what I perceived as gaps. As preload becomes now more important for security reasons it would be very helpful and improve vue electron adoption if this process would not be so challenging. To aid implementation here is my certainly not production ready approach.

**Challenges**: understanding webpack, webpack chaining, the chaining setup in electron builder, vue inspect, the webpack copy plugin, the file layout in the package, __static, define plugin, the asar file system and while experimenting with the copy plugin changed the API in the later releases of version 5 (see https://github.com/webpack-contrib/copy-webpack-plugin/issues/4559 . I may have not taken the straightest path to my solution but I learned a lot in the process so good for me.

**Documentation:**

A) I was initially not clear whether I should deal with preload in the background or render build and looked first at the background build webpack chaining. Please consider some comment in vue.config.js for electron builder like "// The config is different from the render config and can not be examined with "vue inspect". Use console.log(config.toString()) to examine details.". This can help as e.g. I assumed after looking at "vue inspect" the copy plugin is available in the main build and it is not.

B) __static is confusing and would benefit from more documentation. The current documentation says __static is global variable but it is a webpack define and there were two cases where that matters.

B1) In development __static is a string. In production build __static is a piece of code i.e. 'require("electron").remote.app.getAppPath()' that requires electron to run . Electron on the renderer is not available after the init so my attempt to simple log __static in my renderer failed but only in production. 

B2) As there are are also typescript versions of background.ts it would be good if __static came with a typing as otherwise the typescript build fails. I added in my background.ts a line but it would be great if I had not to (and putting it into another file may help to keep TS/JS files same).
```ts
declare let __static: any;
```
**Implementation**

It took me a while to understand that the preload.js file should be in the app.asar file but should not be run through the build pipeline as the BrowserWindow does require an absolute path to the file.  I also learned I could give an absolute path to a file within the .asar due to the specially patched node version in electron. 

Copy during the renderer build in vue.config.js:
```js
             config.plugin('copy').tap(args => {
            args[0].push({ from: 'src/preload.js', to: '' }); // copy to the root of the app.asar file
            return args;
          });
```

Then in background.js

```js
const path = require('path');
function createWindow () {
  const preload = (process.env.NODE_ENV === 'development') ?
                // eslint-disable-next-line no-undef
                  path.resolve(__static, '..', 'src', 'preload.js') : // dev
                // eslint-disable-next-line no-undef
                path.resolve(__static, 'preload.js');  // prod

  // Create the browser window.
  win = new BrowserWindow({ width: 800, height: 600, webPreferences: {
    // [...]
    preload
  } })
```

My preload.js file for completeness
```js
const { ipcRenderer } = require('electron') ;
window.ipcRenderer = ipcRenderer;
```

Hope this helps someone.

**Comment by nklayman** [comment] 2020-07-04 01:37
Duplicate of #613. See https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/guide.html#preload-files for documentation.

Do you have any suggestions for making this more visible so that you would have found it?

**Closed by nklayman** 2020-07-04 01:37 UTC

**Comment by nibbleswap** [comment] 2020-07-10 20:29
Thank you for your answer. I have re-checked with a completely default vue project and can confirm everything works as it should and is really simple. To the degree I still can reconstruct it I was working according to your documentation but with a **typescript** project and created a preload.ts. Not understanding the building process yet I tried different things and then finally started to reinvent the wheel.

I don't think finding the documentation was the issue but what to do in case of typescript. Adding a sentence along the lines of "The preload.js file is copied as-is during the background process build, it is not run through typescript compiler or babel (correct ?) and must be a js file." would be helpful. To aid troubleshooting it may also be helpful to explain that the preload.js file is placed in the root of the app.asar file bundle.

**Comment by nklayman** [comment] 2020-07-14 17:36
The preload file is passed through webpack with the same config as your main process file (although with the target set to `electron-preload`). I just tried a typescript file and it worked fine. Can you create an example repo that shows a `preload.ts` file not working so that I can debug it?

**Comment by abulka** [comment] 2021-12-25 03:38
@nibbleswap In electron 13.6.3 I found that I had to set `contextIsolation` to false otherwise a default vue project and instructions to set up `preload.js` don't work.  See [my comment](https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/949#issuecomment-1000967501).
