### ISSUE TITLE
Updating @vue/cli-service from 3.2.0 to 3.3.1, electron:build blank screen.

### ISSUE THREAD

**Issue by FINDarkside** [nklayman/vue-cli-plugin-electron-builder#184] opened 2019-01-27 16:49 UTC
Updating @vue/cli-service from 3.2.0 to 3.3.1 breaks the build. The urls don't use app protocol anymore, so The script tags look like this:
`<script type="module" src="/js/chunk-vendors.3a2dca96.js"></script>`

And therefore I get errors like `Failed to load resource: net::ERR_FILE_NOT_FOUND /C:/js/chunk-vendors.3a2dca96.js:1`

Unfortunately I  don't have time to troubleshoot more, so I'm not sure whether this is issue with vue-cli or this.

**Comment by nklayman** [comment] 2019-01-27 23:30
Duplicate of #177, make sure you are using latest version of this plug-in.

**Closed** 2019-01-27 23:31 UTC
