### ISSUE TITLE
occur an error after packaging

### ISSUE THREAD

**Issue by 13196789316** [nklayman/vue-cli-plugin-electron-builder#1124] opened 2020-11-03 13:16 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/31721964/97989673-d581c780-1e19-11eb-8110-e496d8a34152.png)

**Environment (please complete the following information):**
 - custom config for vcp-electron-builder: 
 - (if possible) link to your repo: 
 - terminal output from running `vue info`:

**Additional context**
It may happen here :   
`javascript

"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
`

**Comment by 13196789316** [comment] 2020-11-05 04:36
@nklayman   After babel is configured, it can be executed

**Comment by nklayman** [comment] 2020-11-06 06:22
Does that mean that the issue is resolved? If so please close it. Otherwise, I will need you to fill out all the information requested in the bug report template, especially the output from `vue info`, without it I cannot help you.

**Closed** 2020-11-07 08:36 UTC

**Comment by 13196789316** [comment] 2020-11-07 08:38
@nklayman  Thanks.I resovled it.It's the problem of ES6 syntax

**Comment by oceanlvr** [comment] 2021-07-26 10:00
@13196789316 Same problem, how do you solve this?
