### ISSUE TITLE
Struggling to load local files

### ISSUE THREAD

**Issue by chriship** [nklayman/vue-cli-plugin-electron-builder#1014] opened 2020-09-01 10:31 UTC
I'm trying to load an array of video files using the code below. It works with `npm run serve` and builds with `npm run electron:build` but the build does not load the files. I have tried lots of suggestions from #47 but none of them seem to work. I'm on OSX.

```
<template>
    <div v-for="(element, index) in media" :key="index">
        <div :class="{ hidden : index != currentIndex }">
            <video ref="video" :src="getVideo(index)" type="video/mp4" preload="auto" @ended="videoEnded"></video>
        </div>
    </div>
    <button @click="playPause">
        <span v-if="!isPlaying">Play</span>
        <span v-else>Pause</span>
    </button>
</template>

export default {
  name: "Test",
  data() {
    return {
      media: ["video1.mp4", "video2.mp4", "video3.mp4", "video4.mp4"],
      currentIndex: 0,
      isPlaying: false,
    };
  },
  methods: {
    getVideo(index) {
      return require("../assets/" + this.media[index]);
    },
    videoEnded() {
      this.nextVideo();
    },
    nextVideo() {
      this.pause();
      this.currentIndex++;
      this.play();
    },
    playPause() {
      if (this.isPlaying) {
        this.pause();
        this.isPlaying = false;
      } else {
        this.play();
        this.isPlaying = true;
      }
    },
    play() {
      this.$refs.video[this.currentIndex].play();
    },
    pause() {
      if (this.$refs.video[this.currentIndex].readyState == 4) {
        this.$refs.video[this.currentIndex].pause();
      }
    },
  },
};
```

**Comment by chriship** [comment] 2020-09-03 11:28
Update: as I've seen others suggest online, moving down to electron 6 makes this work.

**Comment by nklayman** [comment] 2020-09-04 00:50
This seems like a duplicate of #872. Have you tried the solution posted there?

**Comment by andypotato** [comment] 2020-09-09 09:03
@chriship You can either downgrade to Electron <= 6 or use the solution @nklayman [suggests here](https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/872#issuecomment-656292808).

**Closed** 2020-09-16 15:39 UTC
Labels: awaiting OP response

**Comment by Blunderchips** [comment] 2020-11-17 14:10
@nklayman getting this issue on linux. media files are just missing.
works when served but not when built.

![image](https://user-images.githubusercontent.com/7081037/99400161-4f708100-28ef-11eb-99aa-ec20dd4180bf.png)
