### ISSUE TITLE
Uncaught (in promise) Error: ENOENT, SumatraPDF.exe

### ISSUE THREAD

**Issue by dalholm** [nklayman/vue-cli-plugin-electron-builder#848] opened 2020-06-23 14:17 UTC
**Describe the bug**
I get this error after build for windows. Mac is working perfectly.
`Uncaught (in promise) Error: ENOENT, SumatraPDF.exe not found in C:\Users\dalholm\AppData\Local\Programs\printer-app\resources\app.asar`

**To Reproduce**
add pdf-to-print module and silent print a pdf.

**Expected behavior**
Should send the pdf to printer

**Environment (please complete the following information):**
 - OS and version: Windows 10
 - node version: 12.18.0
 - npm version: 6.14.5
 - vue-cli-plugin-electron-builder version : ^2.0.0-rc.1
 - electron version: 9.0.0
 - other vue plugins used: pdf-to-print

I have been searching for this all over the place. :) But with no luck. The `SumatraPDF.exe` is listed in node_modules as it supose i dont know why its not loaded in windows. 

```js
// vue.config.js
module.exports = {
    pluginOptions: {
        electronBuilder: {
            nodeIntegration: true,
            nodeModulesPath: ['../../node_modules', './node_modules'],
            builderOptions: {
                files: [
                    "**/*"
                  ],
                publish: ['github'],

            }
        }
    }
}```

**Comment by nklayman** [comment] 2020-06-23 17:27
Try:
```js
// vue.config.js
module.exports = {
    pluginOptions: {
        electronBuilder: {
            nodeIntegration: true,
            externals: ['pdf-to-print'], // required for native module to work
            nodeModulesPath: ['../../node_modules', './node_modules'],
            builderOptions: {
                files: [
                    "**/*"
                  ],
                publish: ['github'],

            }
        }
    }
}
```

Also, you should be able to get rid of the `files` config as that is set for you.

**Comment by dalholm** [comment] 2020-06-24 12:04
@nklayman thanks for the answer, but it didn't help. Same error when trying to print in production on windows. :(

```
electron/js2c/asar.js:111 Uncaught (in promise) Error: ENOENT, SumatraPDF.exe not found in C:\Users\dalholm\AppData\Local\Programs\printer-app\resources\app.asar
    at createError (electron/js2c/asar.js:111)
    at module.<computed> (electron/js2c/asar.js:179)
    at chunk-vendors.f0958ef8.js:106
    at new Promise (<anonymous>)
    at e.exports (chunk-vendors.f0958ef8.js:106)
    at Object.e.exports [as print] (chunk-vendors.f0958ef8.js:106)
    at ClientRequest.<anonymous> (app.0a487263.js:1)
    at Object.onceWrapper (events.js:313)
    at ClientRequest.emit (events.js:223)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:583)
```

**Comment by dalholm** [comment] 2020-06-24 12:13
@nklayman the `dist_electron/bundled/node_modules` are empty after build. I suppose that this is where the `pdf-to-print` package should be?

**Comment by nklayman** [comment] 2020-06-24 18:38
Duplicate of #539. It's an issue with pdf-to-print, see https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/539#issuecomment-555764426 for workarounds.

**Closed by nklayman** 2020-06-24 18:38 UTC
