### ISSUE TITLE
Cannot Find module . Error from Worker js using c++ addon

### ISSUE THREAD

**Issue by Kamran95** [nklayman/vue-cli-plugin-electron-builder#1320] opened 2021-04-06 06:52 UTC
**Describe the bug**
Project runs fine when run locally with command npm run electron:serve but gives error when build using command npm run electron:build
[electron-c-plus-plus.zip](https://github.com/nklayman/vue-cli-plugin-electron-builder/files/6262588/electron-c-plus-plus.zip)
used different node loader but nothing seems to be working
**Error**
Cannot find module './build/Release/addon.node'
Require stack:
- electron/js2c/worker_init

**To Reproduce**
- npm install
- node-gyp configure
- node-gyp build
- ./node_modules/.bin/electron-rebuild
- npm run electron:build #to generate build file in dost_electron
- install build file and run error will appear in console

**Expected behavior**
worker should load c++ file build with name addon.node in directory build/release/addon.node and console log 'sum() World'
as in code worker.js line number 8.
it works as expected but gives error in build

C++ code is mentioned in file src/addon.cc

**Environment (please complete the following information):**
- mac os
- node version : 14.16.0
- electron 11

**Additional context**
Project has been added as attachment to run this project use following commands

- npm install
- node-gyp configure
- node-gyp build
- ./node_modules/.bin/electron-rebuild
- npm run electron:serve #to run locally
- npm run electron:build #to generate build file in dost_electron

[electron-c-plus-plus.zip](https://github.com/nklayman/vue-cli-plugin-electron-builder/files/6262593/electron-c-plus-plus.zip)

**Comment by muhammadaqibawaan** [comment] 2021-04-06 12:59
facing same issue. Anyone with any progress kindly help me out

**Comment by Kamran95** [comment] 2021-04-06 13:00
no :( use many node loaders but still no solution found

**Comment by JsBlueCat** [comment] 2021-04-07 23:49
same problem
```
 Launching Electron...
App threw an error during load
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:120:11)
    at dirname (path.js:583:5)
    at Function.getRoot (webpack:///./node_modules/bindings/bindings.js?:146:13)
    at bindings (webpack:///./node_modules/bindings/bindings.js?:55:32)
    at eval (webpack:///./src/background.js?:105:87)
    at Module../src/background.js (D:\stereoRectify\dist_electron\index.js:1802:1)
    at __webpack_require__ (D:\stereoRectify\dist_electron\index.js:20:30)
    at eval (webpack:///multi_./src/background.js?:1:18)
    at Object.0 (D:\stereoRectify\dist_electron\index.js:1813:1)
    at __webpack_require__ (D:\stereoRectify\dist_electron\index.js:20:30)

```

**Comment by nklayman** [comment] 2021-05-22 19:12
Duplicate of #1323, see the comment I posted there for solution.

**Closed by nklayman** 2021-05-22 19:12 UTC
