### ISSUE TITLE
Electron Blank Screen (not calling main.ts)

### ISSUE THREAD

**Issue by RacerDelux** [nklayman/vue-cli-plugin-electron-builder#322] opened 2019-07-03 03:47 UTC
This happened kind of out of the blue. I built my app (which previously worked fine) and this is what happened.
![image](https://user-images.githubusercontent.com/2667344/60561940-13994380-9d1b-11e9-98df-87688ab9220d.png)
I am getting no errors. Background.ts is called, and I know that, but it is clear main.ts is not called, and the vue app is not loaded. I am not 100% sure if the issue lies here, but I am pretty stuck on where to go since I am getting no errors.

Electron: 5.0.6
Vue: 3.8.4
Vue-Electron-Builder: 1.3.5
Windows 10: 1903

**Comment by fankohr** [comment] 2019-07-03 16:46
Did you tried this ?
https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/commonIssues.html#blank-screen-on-builds-but-works-fine-on-serve

**Comment by RacerDelux** [comment] 2019-07-04 00:56
So it looks like disabling vue dev tools fixed it. Why would that be breaking suddenly though?

**Comment by nklayman** [comment] 2019-07-04 01:06
No idea. Maybe you changed something inside your app that caused it. Maybe try going back through commits? Since the issue can't be reproduced and is caused by vue devtools, I'm going to close this issue.

**Closed by nklayman** 2019-07-04 01:06 UTC

**Comment by RacerDelux** [comment] 2019-07-04 01:27
Literally nothing changed lol. I even went back to earlier versions and it is broken there too.
