### ISSUE TITLE
Electron build error package.json

### ISSUE THREAD

**Issue by do-web** [nklayman/vue-cli-plugin-electron-builder#175] opened 2019-01-05 22:58 UTC
**Describe the bug**
I got this error tried to using electron 3 and 4.

 Building app with electron-builder:
  • electron-builder version=20.38.4
  • loaded configuration file=package.json ("build" field)
 ERROR  Error: 'build' in the application package.json (bundled/package.json) is not supported since 3.0 anymore. Please move 'build' into the development package.json (package.json)

It seems that the package.json that are moved to the bundled / dist folder is wrong. It should not be the same as the Project package.json.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS and version: Mac
 - node version: 
 - npm version:
 - yarn version (if used): 
 - vue-cli-plugin-electron-builder version : latest
 - electron version: 4
 - other vue plugins used: 
 - custom config for vcp-electron-builder: 
 - (if possible) link to your repo: 

**Additional context**

**Comment by nklayman** [comment] 2019-01-05 23:00
Duplicate of #171, see solution here: https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/171#issuecomment-451359164.

**Closed by nklayman** 2019-01-05 23:00 UTC
