### ISSUE TITLE
Node v14.16.0 w/ TypeScript 4.1 fails to compile optional chaining only in the main process

### ISSUE THREAD

**Issue by pattrickrice** [nklayman/vue-cli-plugin-electron-builder#1482] opened 2021-07-29 20:56 UTC
**Describe the bug**
Title captures most of it. While upgrading to node version 14.16.0 I changed the tsconfig target settings based on this https://github.com/microsoft/TypeScript/wiki/Node-Target-Mapping. A file with optional chaining in it then failed to compile with `You may need an additional loader to handle the result of these loaders.` 

I was able to fix by applying a webpack/babel configuration only to the main process.

```js
  pluginOptions: {
    electronBuilder: {
      chainWebpackMainProcess: config => {
        config.module
          .rule("babel")
          .before("ts")
          .use("babel")
          .loader("babel-loader")
          .options({
            presets: [["@babel/preset-env", { modules: false }]],
            plugins: ["@babel/plugin-proposal-optional-chaining", "@babel/plugin-proposal-nullish-coalescing-operator"],
          });
      },
    }
  }
```

I'm filing it as a bug since its strange that the main process needed additional configuration on it.

**To Reproduce**
- use node v14.16.0
- add optional chaining to main process somewhere
- `yarn electron:build`

If these do not reproduce I can try to create a repro

**Expected behavior**
Main process shouldn't need additional configuration on it.

**Screenshots**
n/a

**Environment (please complete the following information):**
 - custom config for vcp-electron-builder: TODO
 - (if possible) link to your repo: TODO
 - terminal output from running `vue info`:
 ```console
 ➜  hello-world git:(master) ✗ vue info

Environment Info:

  System:
    OS: macOS 11.5.1
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  Binaries:
    Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
    Yarn: 1.22.11 - ~/.nvm/versions/node/v14.16.0/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v14.16.0/bin/npm
  Browsers:
    Chrome: 92.0.4515.131
    Edge: Not Found
    Firefox: 90.0.2
    Safari: 14.1.2
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.2.1
    @vue/babel-helper-vue-transform-on:  1.0.2
    @vue/babel-plugin-jsx:  1.0.6
    @vue/babel-plugin-transform-vue-jsx:  1.2.1
    @vue/babel-preset-app:  4.5.13
    @vue/babel-preset-jsx:  1.2.4
    @vue/babel-sugar-composition-api-inject-h:  1.2.1
    @vue/babel-sugar-composition-api-render-instance:  1.2.4
    @vue/babel-sugar-functional-vue:  1.2.2
    @vue/babel-sugar-inject-h:  1.2.2
    @vue/babel-sugar-v-model:  1.2.3
    @vue/babel-sugar-v-on:  1.2.3
    @vue/cli-overlay:  4.5.13
    @vue/cli-plugin-babel: ~4.5.0 => 4.5.13
    @vue/cli-plugin-eslint: ~4.5.0 => 4.5.13
    @vue/cli-plugin-router:  4.5.13
    @vue/cli-plugin-typescript: ~4.5.0 => 4.5.13
    @vue/cli-plugin-vuex:  4.5.13
    @vue/cli-service: ~4.5.0 => 4.5.13
    @vue/cli-shared-utils:  4.5.13
    @vue/component-compiler-utils:  3.2.2
    @vue/eslint-config-prettier: ^6.0.0 => 6.0.0
    @vue/eslint-config-typescript: ^7.0.0 => 7.0.0
    @vue/preload-webpack-plugin:  1.1.2
    @vue/web-component-wrapper:  1.3.0
    eslint-plugin-vue: ^6.2.2 => 6.2.2
    typescript: ~4.1.5 => 4.1.6
    vue: ^2.6.11 => 2.6.14
    vue-class-component: ^7.2.3 => 7.2.6
    vue-cli-plugin-electron-builder: ~2.1.1 => 2.1.1
    vue-eslint-parser:  7.10.0
    vue-hot-reload-api:  2.3.4
    vue-loader:  15.9.8 (16.5.0)
    vue-property-decorator: ^9.1.2 => 9.1.2
    vue-style-loader:  4.1.3
    vue-template-compiler: ^2.6.11 => 2.6.14
    vue-template-es2015-compiler:  1.9.1
  npmGlobalPackages:
    @vue/cli: Not Found
```

**Additional context**
```console
➜  ~ vue --version
@vue/cli 4.5.13
➜  ~ vue create hello
➜  ~ nvm use 14.16.0
Now using node v14.16.0 (npm v6.14.11)
➜  ~ vue create hello
^C
➜  ~ vue create hello-world


Vue CLI v4.5.13
? Please pick a preset: Manually select features
? Check the features needed for your project: Choose Vue version, Babel, TS, CSS Pre-processors, Linter
? Choose a version of Vue.js that you want to start the project with 2.x
? Use class-style component syntax? Yes
? Use Babel alongside TypeScript (required for modern mode, auto-detected polyfills, transpiling JSX)? Yes
? Pick a CSS pre-processor (PostCSS, Autoprefixer and CSS Modules are supported by default): Sass/SCSS (with dart-sass)
? Pick a linter / formatter config: Prettier
? Pick additional lint features: Lint on save
? Where do you prefer placing config for Babel, ESLint, etc.? In dedicated config files
? Save this as a preset for future projects? No


Vue CLI v4.5.13
✨  Creating project in /Users/price/hello-world.
🗃  Initializing git repository...
⚙️  Installing CLI plugins. This might take a while...

yarn install v1.22.11
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...


success Saved lockfile.
✨  Done in 43.99s.
🚀  Invoking generators...
📦  Installing additional dependencies...

yarn install v1.22.11
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...

success Saved lockfile.
✨  Done in 18.91s.
⚓  Running completion hooks...

📄  Generating README.md...

🎉  Successfully created project hello-world.
👉  Get started with the following commands:

 $ cd hello-world
 $ yarn serve

➜  ~ vue add electron-builder


➜  ~ cd hello-world
➜  hello-world git:(master) vue add electron-builder



📦  Installing vue-cli-plugin-electron-builder...

yarn add v1.22.11
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...

success Saved lockfile.
success Saved 105 new dependencies.
info Direct dependencies
└─ vue-cli-plugin-electron-builder@2.1.1
info All dependencies
├─ @develar/schema-utils@2.6.5
├─ @electron/universal@1.0.5
├─ @malept/cross-spawn-promise@1.1.1
├─ @malept/flatpak-bundler@0.4.0
├─ @npmcli/move-file@1.1.2
├─ @sindresorhus/is@0.14.0
├─ @szmarczak/http-timer@1.1.2
├─ @types/debug@4.1.7
├─ @types/ms@0.7.31
├─ @types/plist@3.0.2
├─ @types/verror@1.10.5
├─ @types/yargs-parser@20.2.1
├─ @types/yargs@16.0.4
├─ aggregate-error@3.1.0
├─ ansi-align@3.0.0
├─ app-builder-bin@3.5.13
├─ asar@3.0.3
├─ boxen@5.0.1
├─ buffer-equal@1.0.0
├─ cacheable-request@6.1.0
├─ ci-info@3.2.0
├─ clean-stack@2.2.0
├─ cli-boxes@2.2.1
├─ clone-response@1.0.2
├─ colors@1.0.3
├─ configstore@5.0.1
├─ crc@3.8.0
├─ crypto-random-string@2.0.0
├─ decompress-response@3.3.0
├─ deep-extend@0.6.0
├─ defer-to-connect@1.1.3
├─ dir-compare@2.4.0
├─ dmg-builder@22.11.7
├─ dmg-license@1.0.9
├─ duplexer3@0.1.4
├─ electron-builder@22.11.7
├─ electron-publish@22.11.7
├─ escape-goat@2.1.1
├─ filelist@1.0.2
├─ friendly-errors-webpack-plugin@1.7.0
├─ global-dirs@3.0.0
├─ got@9.6.0
├─ graceful-readlink@1.0.1
├─ has-yarn@2.1.0
├─ hosted-git-info@4.0.2
├─ http-cache-semantics@4.1.0
├─ human-signals@2.1.0
├─ iconv-corefoundation@1.1.6
├─ immediate@3.0.6
├─ import-lazy@2.1.0
├─ indent-string@4.0.0
├─ ini@2.0.0
├─ is-installed-globally@0.4.0
├─ is-npm@5.0.0
├─ is-yarn-global@0.3.0
├─ isbinaryfile@4.0.8
├─ jake@10.8.2
├─ jest-worker@26.6.2
├─ json-buffer@3.0.0
├─ jszip@3.7.1
"use strict";
├─ keyv@3.1.0
├─ latest-version@5.1.0
├─ lie@3.3.0
├─ lodash.merge@4.6.2
├─ lowercase-keys@1.0.1
├─ minipass-collect@1.0.2
├─ minipass-flush@1.0.5
├─ minipass-pipeline@1.2.4
├─ minizlib@2.1.2
├─ node-addon-api@1.7.2
├─ p-cancelable@1.1.0
├─ package-json@6.5.0
├─ plist@3.0.3
├─ pumpify@2.0.1
├─ pupa@2.1.1
├─ registry-auth-token@4.2.1
├─ registry-url@5.1.0
├─ responselike@1.0.2
├─ sanitize-filename@1.6.3
├─ semver-diff@3.1.1
├─ set-immediate-shim@1.0.1
├─ shebang-loader@0.0.1
├─ smart-buffer@4.2.0
├─ split2@3.2.2
├─ stat-mode@1.0.0
├─ tar@6.1.6
├─ through2-filter@3.0.0
├─ through2-map@3.0.0
├─ tmp-promise@3.0.2
├─ to-readable-stream@1.0.0
├─ truncate-utf8-bytes@1.0.2
├─ typedarray-to-buffer@3.1.5
├─ unique-string@2.0.0
├─ unzip-crx@0.2.0
├─ update-notifier@5.1.0
├─ url-parse-lax@3.0.0
├─ utf8-byte-length@1.0.4
├─ vue-cli-plugin-electron-builder@2.1.1
├─ widest-line@3.1.0
├─ write-file-atomic@3.0.3
├─ xmlbuilder@15.1.1
├─ xmldom@0.6.0
├─ yaku@0.16.7
├─ yargs@15.4.1
└─ yocto-queue@0.1.0
✨  Done in 18.26s.
✔  Successfully installed plugin: vue-cli-plugin-electron-builder

? Choose Electron Version ^13.0.0

🚀  Invoking generator for vue-cli-plugin-electron-builder...
📦  Installing additional dependencies...

yarn install v1.22.11
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
$ electron-builder install-app-deps
  • electron-builder  version=22.11.7
✨  Done in 21.39s.
⚓  Running completion hooks...

✔  Successfully invoked generator for plugin: vue-cli-plugin-electron-builder
➜  hello-world git:(master) ✗ vim src/background.ts
➜  hello-world git:(master) ✗ vim src/App.vue
➜  hello-world git:(master) ✗ yarn electron:build
yarn run v1.22.11
$ vue-cli-service electron:build
 INFO  Bundling render process:

⠋  Building modern bundle for production...Starting type checking service...
Using 1 worker with 2048MB memory limit
⠙  Building modern bundle for production...

 WARNING  Compiled with 1 warning                                                                                                                                                                                              11:43:55 AM

Module Warning (from ./node_modules/eslint-loader/index.js):

/Users/price/hello-world/src/App.vue
  11:1  warning  Delete `·`  prettier/prettier

✖ 1 problem (0 errors, 1 warning)
  0 errors and 1 warning potentially fixable with the `--fix` option.


You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.
  File                                                  Size                                                                                    Gzipped

  dist_electron/bundled/js/chunk-vendors.2f8211ad.js    70.22 KiB                                                                               24.89 KiB
  dist_electron/bundled/js/app.37f8fcc0.js              4.97 KiB                                                                                1.77 KiB
  dist_electron/bundled/css/app.46d2445d.css            0.33 KiB                                                                                0.23 KiB

  Images and other types of assets omitted.

 DONE  Build complete. The dist_electron/bundled directory is ready to be deployed.
 INFO  Check out deployment instructions at https://cli.vuejs.org/guide/deployment.html

⠼  Bundling main process...

 ERROR  Failed to compile with 1 errors                                                                                                                                                                                        11:43:56 AM

 error  in ./src/background.ts

Module parse failed: Unexpected token (6:12)
File was processed with these loaders:
 * ./node_modules/ts-loader/index.js
You may need an additional loader to handle the result of these loaders.
| import installExtension, { VUEJS_DEVTOOLS } from "electron-devtools-installer";
| const isDevelopment = process.env.NODE_ENV !== "production";
> process.env?.test === "false";
| // Scheme must be registered before the app is ready
| protocol.registerSchemesAsPrivileged([

 @ multi ./src/background.ts

Unhandled rejection Error: Build failed with errors.
    at /Users/price/hello-world/node_modules/vue-cli-plugin-electron-builder/index.js:198:21
    at finalCallback (/Users/price/hello-world/node_modules/webpack/lib/Compiler.js:257:39)
    at /Users/price/hello-world/node_modules/webpack/lib/Compiler.js:273:13
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/price/hello-world/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/price/hello-world/node_modules/tapable/lib/Hook.js:154:20)
    at onCompiled (/Users/price/hello-world/node_modules/webpack/lib/Compiler.js:271:21)
    at /Users/price/hello-world/node_modules/webpack/lib/Compiler.js:681:15
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/price/hello-world/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/price/hello-world/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/price/hello-world/node_modules/webpack/lib/Compiler.js:678:31
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/price/hello-world/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/price/hello-world/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/price/hello-world/node_modules/webpack/lib/Compilation.js:1423:35
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/price/hello-world/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/price/hello-world/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/price/hello-world/node_modules/webpack/lib/Compilation.js:1414:32
    at eval (eval at create (/Users/price/hello-world/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:12:1)
    at /Users/price/hello-world/node_modules/terser-webpack-plugin/dist/index.js:321:9
    at step (/Users/price/hello-world/node_modules/terser-webpack-plugin/dist/TaskRunner.js:87:9)
    at done (/Users/price/hello-world/node_modules/terser-webpack-plugin/dist/TaskRunner.js:98:30)
    at tryCatcher (/Users/price/hello-world/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/price/hello-world/node_modules/bluebird/js/release/promise.js:547:31)

✨  Done in 8.97s.
➜  hello-world git:(master) ✗ cat package.json
{
  "name": "hello-world",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint",
    "electron:build": "vue-cli-service electron:build",
    "electron:serve": "vue-cli-service electron:serve",
    "postinstall": "electron-builder install-app-deps",
    "postuninstall": "electron-builder install-app-deps"
  },
  "main": "background.js",
  "dependencies": {
    "core-js": "^3.6.5",
    "vue": "^2.6.11",
    "vue-class-component": "^7.2.3",
    "vue-property-decorator": "^9.1.2"
  },
  "devDependencies": {
    "@types/electron-devtools-installer": "^2.2.0",
    "@typescript-eslint/eslint-plugin": "^4.18.0",
    "@typescript-eslint/parser": "^4.18.0",
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-plugin-typescript": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "@vue/eslint-config-prettier": "^6.0.0",
    "@vue/eslint-config-typescript": "^7.0.0",
    "electron": "^13.0.0",
    "electron-devtools-installer": "^3.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-prettier": "^3.3.1",
    "eslint-plugin-vue": "^6.2.2",
    "prettier": "^2.2.1",
    "sass": "^1.26.5",
    "sass-loader": "^8.0.2",
    "typescript": "~4.1.5",
    "vue-cli-plugin-electron-builder": "~2.1.1",
    "vue-template-compiler": "^2.6.11"
  }
}
```

**Comment by rehanvdm** [comment] 2021-11-14 19:32
Not a webpack expert here, but pieced this together. Webpack got resolved to v5 in the peer dependencies, especially because node-loader requires webpack v5 or more. So after explicitly installing webpack v4, and node-loader v1, did it work for me. 

```
npm i -D  webpack@"<5.0.0"
npm i -D node-loader@1.0.3
```

`vue-cli-plugin-electron-builder` is not ready for webpack v5 according to this => https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/1326 ? But somehow it got installed and worked?

**Comment by pattrickrice** [comment] 2021-11-16 23:10
@rehanvdm unfortunately that didn't work for me. I tried on my build and get

```console
 INFO  Bundling render process:

⠋  Building modern bundle for production... ERROR  Vue CLI build failed. Please resolve any issues with your build and try again.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by nklayman** [comment] 2022-01-04 03:47
Sorry for the delayed response, had to take a break from open source to focus on school.

It seems like the issue is caused by some weird webpack version resolution. Upgrading to v3 alpha of this plugin (which uses webpack 5) fixed the issue for me. You can find upgrade instructions here: https://github.com/nklayman/vue-cli-plugin-electron-builder/releases/tag/v3.0.0-alpha.0. I'll close this since it's fixed/avoided in the latest version.

**Closed by nklayman** 2022-01-04 03:47 UTC
