### ISSUE TITLE
Blank screen on build (vue-router not used in app)

### ISSUE THREAD

**Issue by yowzadave** [nklayman/vue-cli-plugin-electron-builder#1131] opened 2020-11-09 16:03 UTC
The app runs in dev mode using `yarn electron:serve`, and appears to build successfully using `yarn electron:build`, but running the built app results only in a blank screen. I have seen the issue [here](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/commonIssues.html#blank-screen-on-builds-but-works-fine-on-serve), but I believe it does not apply as my app does not use vue-router.

Running devtools in the production app does not provide a useful stack trace:
```
Uncaught SyntaxError: Strict mode code may not include a with statement
DevTools failed to load SourceMap: Could not load content for app://./js/chunk-vendors.7ded432d.js.map:
```

Vue devtools are not loaded in the production app (despite commenting out the if statement surrounding the `await installExtension(VUEJS_DEVTOOLS)` in the `background.js`.

Related dependency versions: 
```
    "electron": "^9.0.0",
    "electron-devtools-installer": "^3.1.0",
    "vue-cli-plugin-electron-builder": "^2.0.0-rc.5",
```

**Comment by Imokh** [comment] 2020-11-16 06:14
> The app runs in dev mode using `yarn electron:serve`, and appears to build successfully using `yarn electron:build`, but running the built app results only in a blank screen. I have seen the issue [here](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/commonIssues.html#blank-screen-on-builds-but-works-fine-on-serve), but I believe it does not apply as my app does not use vue-router.
> 
> Running devtools in the production app does not provide a useful stack trace:
> 
> ```
> Uncaught SyntaxError: Strict mode code may not include a with statement
> DevTools failed to load SourceMap: Could not load content for app://./js/chunk-vendors.7ded432d.js.map:
> ```
> 
> Vue devtools are not loaded in the production app (despite commenting out the if statement surrounding the `await installExtension(VUEJS_DEVTOOLS)` in the `background.js`.
> 
> Related dependency versions:
> 
> ```
>     "electron": "^9.0.0",
>     "electron-devtools-installer": "^3.1.0",
>     "vue-cli-plugin-electron-builder": "^2.0.0-rc.5",
> ```



> The app runs in dev mode using `yarn electron:serve`, and appears to build successfully using `yarn electron:build`, but running the built app results only in a blank screen. I have seen the issue [here](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/commonIssues.html#blank-screen-on-builds-but-works-fine-on-serve), but I believe it does not apply as my app does not use vue-router.
> 
> Running devtools in the production app does not provide a useful stack trace:
> 
> ```
> Uncaught SyntaxError: Strict mode code may not include a with statement
> DevTools failed to load SourceMap: Could not load content for app://./js/chunk-vendors.7ded432d.js.map:
> ```
> 
> Vue devtools are not loaded in the production app (despite commenting out the if statement surrounding the `await installExtension(VUEJS_DEVTOOLS)` in the `background.js`.
> 
> Related dependency versions:
> 
> ```
>     "electron": "^9.0.0",
>     "electron-devtools-installer": "^3.1.0",
>     "vue-cli-plugin-electron-builder": "^2.0.0-rc.5",
> ```



> The app runs in dev mode using `yarn electron:serve`, and appears to build successfully using `yarn electron:build`, but running the built app results only in a blank screen. I have seen the issue [here](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/commonIssues.html#blank-screen-on-builds-but-works-fine-on-serve), but I believe it does not apply as my app does not use vue-router.
> 
> Running devtools in the production app does not provide a useful stack trace:
> 
> ```
> Uncaught SyntaxError: Strict mode code may not include a with statement
> DevTools failed to load SourceMap: Could not load content for app://./js/chunk-vendors.7ded432d.js.map:
> ```
> 
> Vue devtools are not loaded in the production app (despite commenting out the if statement surrounding the `await installExtension(VUEJS_DEVTOOLS)` in the `background.js`.
> 
> Related dependency versions:
> 
> ```
>     "electron": "^9.0.0",
>     "electron-devtools-installer": "^3.1.0",
>     "vue-cli-plugin-electron-builder": "^2.0.0-rc.5",
> ```

I also encountered the same problem, but I used the Vue-Router, and the routing mode configured the hash mode according to the official website.After packaging is still blank, the development environment is normal.The plugin version is the same as the questioner.

**Comment by Imokh** [comment] 2020-11-16 06:14
I also encountered the same problem, but I used the Vue-Router, and the routing mode configured the hash mode according to the official website.After packaging is still blank, the development environment is normal.The plugin version is the same as the questioner.

**Comment by LUK3D** [comment] 2020-12-02 17:41
Same here

**Comment by pseudo-god** [comment] 2020-12-09 04:12
I also encountered it, and I solved it by lowering the version of electron.

**Comment by nklayman** [comment] 2020-12-13 23:21
Can someone create a repo that demonstrates this error and share it here? I can't reproduce the error myself and therefore cannot help debug it. Thanks!

**Comment by NickeManarin** [comment] 2020-12-15 13:23
@nklayman I'm also facing the same issue.

The `electron:serve` command works fine, but `electron:build` does not.
I'm generating a portable dist, not sure if it helps.

https://github.com/NickeManarin/Franchise-Map/tree/dev

**Comment by huqiliang** [comment] 2020-12-18 06:44
> I also encountered it, and I solved it by lowering the version of electron.

To what version ? Is just change vue-cli-plugin-electron-builder version ? I have the same issue.

**Comment by nklayman** [comment] 2021-01-04 22:42
@NickeManarin your app uses history mode, which is a separate issue from the one originally posted. See [this section of the docs](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/commonIssues.html#blank-screen-on-builds-but-works-fine-on-serve) for how to fix your issue.

I am going to close this issue for now as no one has sent me an example repo that demonstrates the original error for this issue. Once I get an example repo, I will reopen this and look into it.

**Closed by nklayman** 2021-01-04 22:42 UTC
